### ISSUE TITLE
download failure

### ISSUE THREAD

**Issue by snakehaihai** [3DOM-FBK/MIN3D#1]
Hi

Thanks for making such a good dataset. 

But when I download this dataset, there is frequent download failure issue from the server. Is there any google drive option there so that we can use the tools to download and avoid failure connection issue?

Rgs

Shenghai Yuan

**Comment by trybala** [comment]
Hi Yuan
The data is not available on Google Drive. If you have unstable connection issues, you can try using a download manager that can resume interrupted downloads. I just verified that JDownloader works well with the links in this repo
Cheers
Pawel

**Comment by snakehaihai** [comment]
Hi Pawel

Ok thanks, I`ll try it.

Rgs
Shenghai Yuan
